package com.github.lbroudoux.products.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-730033
 * 2019-03-19T10:24:35.997+01:00
 * Generated source version: 3.2.7.fuse-730033
 *
 */
@WebService(targetNamespace = "http://ws.products.lbroudoux.github.com/", name = "ProductEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductEndpoint {

    @WebMethod
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://ws.products.lbroudoux.github.com/", className = "com.github.lbroudoux.products.ws.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://ws.products.lbroudoux.github.com/", className = "com.github.lbroudoux.products.ws.GetProductsResponse")
    @WebResult(name = "product", targetNamespace = "")
    public java.util.List<com.github.lbroudoux.products.ws.Product> getProducts(
        @WebParam(name = "category", targetNamespace = "")
        java.lang.String category
    );

    @WebMethod
    @RequestWrapper(localName = "getProductByName", targetNamespace = "http://ws.products.lbroudoux.github.com/", className = "com.github.lbroudoux.products.ws.GetProductByName")
    @ResponseWrapper(localName = "getProductByNameResponse", targetNamespace = "http://ws.products.lbroudoux.github.com/", className = "com.github.lbroudoux.products.ws.GetProductByNameResponse")
    @WebResult(name = "product", targetNamespace = "")
    public com.github.lbroudoux.products.ws.Product getProductByName(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
