package com.github.lbroudoux.products.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-730033
 * 2019-03-19T10:24:36.036+01:00
 * Generated source version: 3.2.7.fuse-730033
 *
 */
@WebServiceClient(name = "ProductEndpointService",
                  wsdlLocation = "file:/Users/lbroudou/Development/local/tests/api-pastry-fuse-impl/src/main/resources/product-service.wsdl",
                  targetNamespace = "http://ws.products.lbroudoux.github.com/")
public class ProductEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.products.lbroudoux.github.com/", "ProductEndpointService");
    public final static QName ProductEndpointPort = new QName("http://ws.products.lbroudoux.github.com/", "ProductEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/lbroudou/Development/local/tests/api-pastry-fuse-impl/src/main/resources/product-service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/lbroudou/Development/local/tests/api-pastry-fuse-impl/src/main/resources/product-service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProductEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ProductEndpoint
     */
    @WebEndpoint(name = "ProductEndpointPort")
    public ProductEndpoint getProductEndpointPort() {
        return super.getPort(ProductEndpointPort, ProductEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductEndpoint
     */
    @WebEndpoint(name = "ProductEndpointPort")
    public ProductEndpoint getProductEndpointPort(WebServiceFeature... features) {
        return super.getPort(ProductEndpointPort, ProductEndpoint.class, features);
    }

}
