camel:
  springboot:
    # The Camel context name
    name: API Pastry
  component:
    servlet:
      mapping:
        contextPath: /*

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

product-ws-url: ${PRODUCT_WS_URL:http://localhost:8082/soap/ProductService/1.0.0}
kafka-broker-url: ${KAFKA_BROKER_URL:my-cluster-kafka-bootstrap.amq-streams.svc.cluster.local:9092}
